### ISSUE TITLE
Allow to start vimade disabled

### ISSUE THREAD

**Issue by hupfdule** [TaDaa/vimade#25] opened 2019-07-08 08:28 UTC
It seems that there is no option to start vimade disabled and having to activate it via VimadeEnable.
I think such an option could help to work around problems like #24.

**Comment by TaDaa** [comment] 2019-07-08 15:44
Added some documentation and cleaned up some logic to support this -- 
You can use either 
```let g:vimade_running=0```
```call vimade#Disable()```
```VimadeDisable``` - the command may or may not work during startup depending on the plugin manager.

to disable during startup.  You shouldn't need to do this anymore though, the garbage characters were likely being caused by detecttermcolors, which I've now set to disabled by default.

**Comment by hupfdule** [comment] 2019-07-09 06:53
Hmm, I tried with `let g:vimade_running=0`, but still vimade is enabled on startup.

**Comment by TaDaa** [comment] 2019-07-09 15:39
Strange -- will need more info, what is the indication that vimade is still enabled -- are the buffers still fading or something else?

Also can you verify that g:vimade_running is still 0 after vim has loaded?

**Comment by hupfdule** [comment] 2019-07-10 07:09
Well I could have done that in the first place… Didn't think about it, sorry.
Yes, I can see that vimade is enabled, since it does fade the content of my windows. 
And the result of `echo g:vimade_running` is: `1`.

Now I have tried around a bit and found the following.

I am using the [Volt package manager for vim 8](https://github.com/vim-volt/volt) where I can define configuration settings to be done per package _before_ a package is loaded or _after_ a package is loaded.

I have played around with setting `g:vimade_running` before and after loading the package and calling `nvim -o file1 file2` and I still see a difference:

1. Not setting `g:vimade_running` at all
![not_set](https://user-images.githubusercontent.com/36069345/60947620-429e4f00-a2f1-11e9-829e-72ccd5f170c1.png)

2. Setting `g:vimade_running` _before_ loading the package
![before](https://user-images.githubusercontent.com/36069345/60947665-65c8fe80-a2f1-11e9-95b4-5e04c43d2efb.png)

3. Setting `g:vimade_running` _after_ loading the package
![after](https://user-images.githubusercontent.com/36069345/60947726-99a42400-a2f1-11e9-9906-a828999111e6.png)


In all three cases the value of `g:vimade_running` is `1`. But you can also see that when setting it to `0` _before_ loading the package the dimming of the lower, non-active window doesn't get activated. However, as soon as I switch the focus to the lower window, the upper window gets dimmed. That corresponds to the setting of `g:vimade_running=1`, of course.

So it seems that the setting of `g:vimade_running = 0` is working correctly, but gets overwritten at some time when loading the plugin.

**Comment by TaDaa** [comment] 2019-07-12 15:07
Will take a look as soon as I get a chance -- do you have a minimal vimrc that I can use?  If not I'll try to recreate with volt.

**Comment by hupfdule** [comment] 2019-07-15 06:47
I tried to provide a minimal vimrc to reproduce it, but it doesn't happen there.

So I tried using volt, but also with no other plugins and an empty .vimrc and it still doesn't happen.

So there seems to be a conflicting plugin or setting in my vimrc.

**Comment by TaDaa** [comment] 2024-08-12 03:12
Closing out older issues that were either fixed or could have been external conflicts.  Thanks for filing the report and re-open if needed!

**Closed by TaDaa** 2024-08-12 03:12 UTC
