### ISSUE TITLE
vimade doesn't seem to be doing anything in terminal mode

### ISSUE THREAD

**Issue by yunake** [TaDaa/vimade#1] opened 2019-01-15 04:25 UTC
Great plugin! I've installed using native vim rtp loading and it seems to be working fine in GUI, but it isn't doing anything in terminal mode. How can i efficiently debug this issue? I'm using Tango palette in gnome-terminal and tilda, inside and outside of tmux, and 256 color support is working just fine, even true color in the apps that support it.

**Comment by TaDaa** [comment] 2019-01-15 06:52
Terminal is still a wip, currently it only supports the xterm 256 palette, but I can take a look as soon as I get some free time to see about adding gnome + tilda.  Which colorscheme are you using?

**Comment by ryanp97** [comment] 2019-01-15 08:37
I'm experiencing the same on Alacritty and Tmux. I'm using quantum

**Comment by Ch00k** [comment] 2019-01-15 08:42
Second that. tmux + alacritty + base16 color schemes (both bash and vim).

**Comment by lervag** [comment] 2019-01-15 09:03
I use a solarized palette in urxvt.

**Comment by ryanp97** [comment] 2019-01-15 09:12
It seems to work on Alacritty if you set termguicolors, but if possible, it would be nice to have it function without termguicolors being set.

**Comment by TaDaa** [comment] 2019-01-17 15:21
pushed a fix where the normalid couldn't be resolved in some terminals, see if this resolves the issues for you guys

**Comment by daf** [comment] 2019-01-17 15:35
Happened again but I can't reproduce it faithfully at all:

```
~ -> vim ~/tmp/dumpff.py 
Error detected while processing function vimade#CheckWindows[5]..provider#python3#Call:
line   18:
Invalid channel: 2~ ->
```

shows up on exit.  Probably 1 in 15 exits will have this shown.

**Comment by TaDaa** [comment] 2019-01-17 16:12
always a complaint on line 18?

Also you on vim or neovim?  I do see some similar errors floating around on neovim -- but I'll have to get neovim setup later on my VM to debug

**Comment by Ch00k** [comment] 2019-01-17 16:16
> see if this resolves the issues for you guys

no difference in my case, unfortunately :(

**Comment by TaDaa** [comment] 2019-01-17 16:33
@Ch00k sorry about that -- its taking me some time to setup alacritty (only have it working on mac atm) -- which OS are you using alacritty on? -- Also what is your output for "echo &t_Co" and "echo g:vimade"?

**Comment by Ch00k** [comment] 2019-01-17 20:23
@TaDaa I use macOS 10.13.6. I just tried to run vim inside and outside of tmux, and both the echo's produce the same result:
```
256
{'basebg': '', 'basefg': '', 'fadelevel': 0.4, 'rowbufsize': 30, 'colbufsize': 30, 'normalid': 84, 'checkinterval': 32}
```

**Comment by TaDaa** [comment] 2019-01-17 22:53
Running 10.14.1, works in alacritty + tmux 2.8 for me (unless I set termguicolors, that seems to break syntax highlighting in general).  Does your :messages contain errors? Is syntax highlighting normally?  Does vimade work in Alacritty by itself, if not does it work in the default terminal?

**Comment by TaDaa** [comment] 2019-01-18 22:55
You may see some change now!  For terminal there was a possibility that ctermfg/ctermbg does not get set (when it uses the terminal defaults). There isn't a 100% way of getting the terminal settings (and tmux n, but Vimade should at least try now and default to 0/248 if it can't.

I think for best results on Alacritty, vimade needs a colorscheme that specifies Normal or vimade needs to be configured using g:vimade.basebg and g:vimade.basefg.  I could not find a way to make Alacritty print out the colors like other xterm terminals could (so if any of you know how, let me know -- I may ask on their github later if not)

**Comment by TaDaa** [comment] 2019-01-19 00:20
Spoke too soon, almost there

**Comment by typoman** [comment] 2019-01-23 11:47
I can confirm the plugin works for native OSX (10.13.6) terminal app (xterm-256color).

**Comment by Ch00k** [comment] 2019-01-24 10:57
The latest code works for me in tmux with vim base16 colorscheme. Although vim startup is pretty slow now, and `:messages` still shows this:
```
Vimade: could not load terminal ansi colors, trying tmux...
Vimade: could not load tmux colors, make sure you either use a colorscheme that defines a background and foreground for 'Normal' or configure g:vimade.basefg and g:vimade.basebg
```

**Comment by yifeikong** [comment] 2019-01-25 04:55
> The latest code works for me in tmux with vim base16 colorscheme. Although vim startup is pretty slow now, and `:messages` still shows this:
> 
> ```
> Vimade: could not load terminal ansi colors, trying tmux...
> Vimade: could not load tmux colors, make sure you either use a colorscheme that defines a background and foreground for 'Normal' or configure g:vimade.basefg and g:vimade.basebg
> ```
> 
> I have no custom vimade variables defined in my vimrc.

Same Issue here

**Comment by TaDaa** [comment] 2019-01-25 17:09
Slowness should be fixed now guys and messages should be gone -- the terminal support should overall be a better experience I am hoping...

Here is what is supported:
autodetection of terminal background and foreground colors for vim8 tilix, kitty, gnome, and any other terminal that can correctly return the background/foreground ansi requests.  Tmux is also supported on the previously mentioned terminals (tmux depends on the terminal and then wraps the response in its own request code).

Neovim is not supported for autodetection of background/foreground yet...I am working on it and have a partially working hack but it requires hijacking the UI tty (since neovim is actually not the tty).  I am a bit hesitant to put the hack in because its a bit fragile, but it might lead me to a better solution soon.  However at least vimade will default to fades based on &background, which might be good enough now instead of doing nothing.

**Comment by TaDaa** [comment] 2019-01-25 21:18
Couple of Alacritty users here, so I opened an issue on Alacritty git regarding the ANSI codes not working, maybe they have an alternative

**Comment by Leeshe** [comment] 2019-06-18 10:00
NVIM v0.4.0-762-g9420a2127 (AppImage), gnome-terminal

After having installed vimade with Vim-Plug: `Plug 'TaDaa/vimade'`, it looks like vimade hasn't been added correctly, command `VimadeEnable` is not recognized (same for others commands). Any idea?

**Comment by benfrain** [comment] 2020-04-06 17:20
Neovim v0.4.3 and [Nord theme](https://github.com/arcticicestudio/nord-vim), using iTerm2 v3.3.9.

I'm a front-end dev so entirely possible I'm doing something stupid but very little seems to change between panes. Attaching a grab whereby the top pane is active — notice that only some characters get dimmed/re-colored and line-numbers are unaffected. This is using this config for vimmade:

```
let g:vimade = {}
let g:vimade.fadelevel = 0.4
let g:vimade.enablesigns = 1
```

<img width="1499" alt="Screenshot 2020-04-06 at 18 18 25" src="https://user-images.githubusercontent.com/1318466/78586384-471d7700-7833-11ea-9470-c31bd92f1871.png">

**Comment by TaDaa** [comment] 2020-04-06 17:50
May need a minimal vimrc/init.vim and I'll try to reproduce the issue.

Also are you using tmux and is nvim using termguicolors or is it in 256 color mode?

**Comment by benfrain** [comment] 2020-04-06 18:30
@TaDaa Hi! no tmux, my [init.vim is here](https://gist.github.com/benfrain/4fe3aa3f54101d4565911998218ed724) - that was saved up just before adding vimade as per earlier comment.

**Comment by TaDaa** [comment] 2020-04-07 15:53
Thanks @benfrain 

Few questions:
- Can you confirm the output of `echo $TERM`? 
- What is the output of `echo &termguicolors`
- If $TERM outputs something that is strange, can you try exiting nvim and setting TERM to `xterm-256color.`

**Comment by benfrain** [comment] 2020-04-08 09:33
> Thanks @benfrain
> 
> Few questions:
> 
> * Can you confirm the output of `echo $TERM`?
=> xterm-256color
> * What is the output of `echo &termguicolors`
=> 0
> * If $TERM outputs something that is strange, can you try exiting nvim and setting TERM to `xterm-256color.`

BTW - I have noticed that if I open a split with `:sp` the new pane doesn't get highlighted. If I open my 'init.vim' file with my shortcut `nnoremap <Leader>v :vsp $MYVIMRC<CR>` that does make the other panes fade. 

Is that because the `:sp` is opening the same file rather than a different one, so it doesn't know to dim it??

**Comment by TaDaa** [comment] 2020-04-08 13:56
That is right, `:sp` and `:sp` won't dim because its the same buffer (until the buffer changes via buffer switch, new, etc)

The partial highlighting is still strange to me, I have not been able to reproduce the issue, but we are also seeing different results in 256color mode (my background shows as black and not the nord theme).

It is possible that in 256color the approximation for the fade somehow calculated too close to the Normal ctermfg, which would result in the same color text.  Might be worth trying to adjust the fadelevel to 0.3 or 0.2 and see if the text changes color at all.  I will see termguicolors produces much better results if its an option for you.

**Comment by TaDaa** [comment] 2024-11-03 14:36
Closing this issue as the original issue regarding terminals has long been fixed.  The latest update includes additional support for Neovim as well.

**Closed by TaDaa** 2024-11-03 14:36 UTC
